function exportResults(logs, params)
% exportResults  Write per-channel CSVs to data/ folder.
%
%   exportResults(logs, params)
%
%   time vector is reconstructed from log length (step indices).
%   Real timestamps (in seconds) are written by exportDataset.

    if ~exist('data', 'dir')
        mkdir('data');
    end

    N    = size(logs.logP, 2);
    time = (0:N-1)';   % step index column; real seconds in master_dataset.csv

    writetable(array2table([time logs.logP'], ...
        'VariableNames', ["time_step" params.nodeNames+"_pressure_bar"]), ...
        'data/pressure.csv');

    writetable(array2table([time logs.logQ'], ...
        'VariableNames', ["time_step" params.edgeNames+"_flow_kgs"]), ...
        'data/flow.csv');

    writetable(array2table([time logs.logTemp'], ...
        'VariableNames', ["time_step" params.nodeNames+"_temp_K"]), ...
        'data/temperature.csv');

    writetable(array2table([time logs.logRho'], ...
        'VariableNames', ["time_step" params.nodeNames+"_density"]), ...
        'data/density.csv');

    writetable(array2table([time logs.logPow' logs.logHead' logs.logEff' logs.logCompRatio'], ...
        'VariableNames', ["time_step", "comp_power_W", "comp_head_Jkg", "comp_eff", "comp_ratio"]), ...
        'data/compressor_power.csv');

    writetable(array2table([time logs.logEst'], ...
        'VariableNames', ["time_step" params.nodeNames+"_p_ekf" params.edgeNames+"_q_ekf"]), ...
        'data/ekf_estimates.csv');

    writetable(array2table([time logs.logResP'], ...
        'VariableNames', ["time_step" params.nodeNames+"_ekf_residual"]), ...
        'data/ekf_residuals.csv');

    writetable(array2table([time logs.logRough'], ...
        'VariableNames', ["time_step" params.edgeNames+"_roughness"]), ...
        'data/roughness.csv');

    writetable(array2table([time logs.logPlcP' logs.logPlcQ'], ...
        'VariableNames', ["time_step" params.nodeNames+"_plcReg_p" params.edgeNames+"_plcReg_q"]), ...
        'data/plc_sensor_bus.csv');

    writetable(array2table([time logs.logActComp' logs.logActValve'], ...
        'VariableNames', ["time_step", "actuator_comp_ratio", "actuator_valve_cmd"]), ...
        'data/actuator_commands.csv');

    disp('[export] All CSVs written to the "data" folder.');
end